# Generated by Django 5.0.6 on 2024-07-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_age', models.PositiveIntegerField()),
                ('user_city', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('user_age', models.PositiveIntegerField()),
                ('user_city', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_image', models.CharField(max_length=200)),
            ],
        ),
    ]
